spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: product-service
  redis:
    host: host.docker.internal
    port: 6379
    password: # Leave blank if no password is set
    timeout: 6000

context:
       path: product-service

logging:
  file:
    name: logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO
  logback:
    rollingpolicy:
      max-size: 10MB
      max-history: 10




