spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: order-service

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    root: INFO
  logback:
    rollingpolicy:
      max-size: 10MB
      max-history: 10